# Generated by Django 3.2 on 2021-04-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='product_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
